import { GameProject } from '../types';
import { 
  generateWindowsJavaGame, 
  generateWindowsBatchScript, 
  generateGradleBuild, 
  generateMavenPom 
} from './javaRunner';

export interface GitHubUser {
  login: string;
  id: number;
  avatar_url: string;
  html_url: string;
  name: string | null;
  public_repos: number;
  total_private_repos?: number;
}

export interface GitHubRepo {
  id: number;
  name: string;
  full_name: string;
  private: boolean;
  html_url: string;
  description: string | null;
  default_branch: string;
  updated_at: string;
}

export interface GitHubFileToPush {
  path: string;
  content: string;
  description: string;
  category: 'engine' | 'source' | 'web' | 'config' | 'docs';
  included: boolean;
}

export interface PushProgress {
  currentFileIndex: number;
  totalFiles: number;
  currentFileName: string;
  status: 'idle' | 'preparing' | 'validating' | 'uploading' | 'completed' | 'failed';
  message: string;
  percentage: number;
  error?: string;
  repoUrl?: string;
  branchName?: string;
}

// UTF-8 safe base64 encoding (handles emojis, unicode chars in game text)
export function utf8ToBase64(str: string): string {
  try {
    return btoa(unescape(encodeURIComponent(str)));
  } catch (e) {
    // Fallback using TextEncoder
    const bytes = new TextEncoder().encode(str);
    let binary = '';
    for (let i = 0; i < bytes.byteLength; i++) {
      binary += String.fromCharCode(bytes[i]);
    }
    return btoa(binary);
  }
}

/**
 * Generates all Godot engine, Java, Web, and config source files
 * representing the full game project for GitHub.
 */
export function generateProjectSourceFiles(project: GameProject): GitHubFileToPush[] {
  const cleanName = project.name.replace(/[^a-zA-Z0-9_-]/g, '_') || 'MyGodotGame';
  const playerEntity = project.entities.find(e => e.type === 'player');
  const enemies = project.entities.filter(e => e.type === 'enemy');
  const coins = project.entities.filter(e => e.type === 'coin');
  const obstacles = project.entities.filter(e => e.type === 'obstacle');

  // 1. Godot 4.x project.godot
  const godotProjectConfig = `; Engine configuration file.
; Generated automatically by Godot Engine Studio
config_version=5

[application]
config/name="${project.name.replace(/"/g, '\\"')}"
config/description="${(project.description || '2D/3D Indie Game built with Godot Engine Studio').replace(/"/g, '\\"')}"
run/main_scene="res://Main.tscn"
config/features=PackedStringArray("4.3", "Forward Plus")
boot_splash/bg_color=Color(0.08, 0.1, 0.14, 1)

[display]
window/size/viewport_width=960
window/size/viewport_height=540
window/stretch/mode="canvas_items"
window/stretch/aspect="keep"

[rendering]
renderer/rendering_method="forward_plus"
textures/canvas_textures/default_texture_filter=0
environment/defaults/default_clear_color=Color(0.07, 0.09, 0.13, 1)

[physics]
2d/default_gravity=980.0
2d/default_gravity_vector=Vector2(0, 1)
`;

  // 2. Godot Main.tscn Scene File
  const godotMainScene = `[gd_scene load_steps=3 format=3 uid="uid://${cleanName.toLowerCase()}_main"]

[ext_resource type="Script" path="res://Scripts/PlayerController.gd" id="1_player_script"]

[sub_resource type="RectangleShape2D" id="RectangleShape2D_player"]
size = Vector2(${playerEntity?.width || 32}, ${playerEntity?.height || 32})

[node name="Main" type="Node2D"]

[node name="Camera2D" type="Camera2D" parent="."]
position = Vector2(480, 270)
zoom = Vector2(1, 1)

[node name="WorldEnvironment" type="Node2D" parent="."]

${project.entities.map((e, idx) => `
[node name="${e.name.replace(/[^a-zA-Z0-9_]/g, '_')}" type="CharacterBody2D" parent="."]
position = Vector2(${e.x}, ${e.y})
${e.type === 'player' ? `script = ExtResource("1_player_script")` : ''}

[node name="ColorRect" type="ColorRect" parent="${e.name.replace(/[^a-zA-Z0-9_]/g, '_')}"]
offset_left = -${e.width / 2}
offset_top = -${e.height / 2}
offset_right = ${e.width / 2}
offset_bottom = ${e.height / 2}
color = Color(${hexToRgbNormalized(e.color)})

[node name="CollisionShape2D" type="CollisionShape2D" parent="${e.name.replace(/[^a-zA-Z0-9_]/g, '_')}"]
shape = SubResource("RectangleShape2D_player")
`).join('\n')}
`;

  // 3. Godot Scripts/PlayerController.gd
  const playerGdScript = `extends CharacterBody2D
# Generated by Godot Engine Studio for: ${project.name}

const SPEED = ${playerEntity?.speed ? playerEntity.speed * 20 : 250}.0
const JUMP_VELOCITY = -450.0

var gravity = ProjectSettings.get_setting("physics/2d/default_gravity")
var score: int = 0
var health: int = ${playerEntity?.health || 100}

func _physics_process(delta: float) -> void:
\t# Add gravity if in the air
\tif not is_on_floor():
\t\tvelocity.y += gravity * delta

\t# Handle Jump
\tif Input.is_action_just_pressed("ui_accept") and is_on_floor():
\t\tvelocity.y = JUMP_VELOCITY

\t# Get the input direction: -1, 0, 1
\tvar direction := Input.get_axis("ui_left", "ui_right")
\tif direction:
\t\tvelocity.x = direction * SPEED
\telse:
\t\tvelocity.x = move_toward(velocity.x, 0, SPEED)

\tmove_and_slide()

func add_score(amount: int) -> void:
\tscore += amount
\tprint("Score: ", score)

func take_damage(amount: int) -> void:
\thealth -= amount
\tprint("Health: ", health)
\tif health <= 0:
\t\tget_tree().reload_current_scene()
`;

  // 4. Java Desktop Source File (src/main/java/Main.java)
  const javaSource = generateWindowsJavaGame(project);

  // 5. Standalone Playable HTML5 Game (index.html)
  const webGameHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(project.name)}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      background: #0d1117;
      color: #e6edf3;
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      min-height: 100vh;
      overflow: hidden;
    }
    #game-container {
      position: relative;
      border: 2px solid #30363d;
      border-radius: 12px;
      box-shadow: 0 20px 40px rgba(0,0,0,0.6);
      overflow: hidden;
      background: #000;
    }
    canvas { display: block; }
    #hud {
      position: absolute;
      top: 12px;
      left: 14px;
      right: 14px;
      display: flex;
      justify-content: space-between;
      font-weight: 700;
      font-size: 14px;
      font-family: monospace;
      color: #58a6ff;
      text-shadow: 0 2px 4px rgba(0,0,0,0.8);
      pointer-events: none;
    }
    #controls-hint {
      margin-top: 12px;
      font-size: 12px;
      color: #8b949e;
      text-align: center;
    }
  </style>
</head>
<body>
  <div id="game-container">
    <div id="hud">
      <span id="score-text">SCORE: 0</span>
      <span id="health-text">HP: 100</span>
    </div>
    <canvas id="canvas" width="800" height="450"></canvas>
  </div>
  <div id="controls-hint">
    🎮 Controls: <strong>Arrow Keys / WASD</strong> to Move • <strong>Space</strong> to Jump/Action
  </div>

  <script>
    const canvas = document.getElementById('canvas');
    const ctx = canvas.getContext('2d');
    const scoreText = document.getElementById('score-text');
    const healthText = document.getElementById('health-text');

    const projectData = ${JSON.stringify(project)};
    let player = projectData.entities.find(e => e.type === 'player') || { x: 100, y: 300, width: 32, height: 32, color: '#3b82f6', speed: 5 };
    let entities = JSON.parse(JSON.stringify(projectData.entities.filter(e => e.type !== 'player')));
    let score = 0;
    let health = 100;
    let keys = {};
    let velX = 0, velY = 0;
    let isGrounded = false;
    const gravity = 0.5;

    window.addEventListener('keydown', e => { keys[e.key] = true; });
    window.addEventListener('keyup', e => { keys[e.key] = false; });

    function update() {
      // Horizontal movement
      velX = 0;
      if (keys['ArrowLeft'] || keys['a'] || keys['A']) velX = -player.speed;
      if (keys['ArrowRight'] || keys['d'] || keys['D']) velX = player.speed;

      // Jump
      if ((keys['ArrowUp'] || keys['w'] || keys['W'] || keys[' ']) && isGrounded) {
        velY = -10;
        isGrounded = false;
      }

      // Gravity
      velY += gravity;
      player.x += velX;
      player.y += velY;

      // Ground floor check
      if (player.y >= 380) {
        player.y = 380;
        velY = 0;
        isGrounded = true;
      }

      // Screen boundary
      if (player.x < 0) player.x = 0;
      if (player.x > canvas.width - player.width) player.x = canvas.width - player.width;

      // Collision with entities
      for (let i = entities.length - 1; i >= 0; i--) {
        const ent = entities[i];
        if (
          player.x < ent.x + ent.width &&
          player.x + player.width > ent.x &&
          player.y < ent.y + ent.height &&
          player.y + player.height > ent.y
        ) {
          if (ent.type === 'coin') {
            score += 10;
            entities.splice(i, 1);
          } else if (ent.type === 'enemy') {
            health = Math.max(0, health - 1);
          }
        }
      }

      scoreText.innerText = 'SCORE: ' + score;
      healthText.innerText = 'HP: ' + health;
    }

    function render() {
      ctx.fillStyle = '#161b22';
      ctx.fillRect(0, 0, canvas.width, canvas.height);

      // Draw ground
      ctx.fillStyle = '#21262d';
      ctx.fillRect(0, 412, canvas.width, 38);

      // Draw entities
      entities.forEach(ent => {
        ctx.fillStyle = ent.color || '#238636';
        ctx.fillRect(ent.x, ent.y, ent.width, ent.height);
      });

      // Draw player
      ctx.fillStyle = player.color || '#58a6ff';
      ctx.fillRect(player.x, player.y, player.width, player.height);
    }

    function loop() {
      update();
      render();
      requestAnimationFrame(loop);
    }
    loop();
  </script>
</body>
</html>`;

  // 6. Professional GitHub README.md
  const readmeContent = `# 🎮 ${project.name}

> ${project.description || 'A 2D game created with Godot Engine Studio'}

[![Godot Engine](https://img.shields.io/badge/Godot-4.3-blue.svg?logo=godotengine)](https://godotengine.org/)
[![Java](https://img.shields.io/badge/Java-17%2B-orange.svg?logo=openjdk)](https://www.oracle.com/java/)
[![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT)

---

## 🌟 Overview
**${project.name}** is an indie game project built with **Godot Engine Studio**. It is packaged with dual-target implementations:
1. **Godot 4 Engine Source** (\`project.godot\` and \`Main.tscn\`) ready to import directly into the official Godot Editor.
2. **Native 60FPS Java Swing Desktop Runner** (\`src/Main.java\` and \`Run_Game.bat\`) for standalone Windows and cross-platform execution.
3. **Playable Web Build** (\`index.html\`) ready for GitHub Pages hosting!

### 🎯 Game Stats & Features
- **Genre:** \`${project.genre.toUpperCase()}\`
- **Total Scene Entities:** ${project.entities.length}
- **Player HP:** ${playerEntity?.health || 100} | **Speed:** ${playerEntity?.speed || 5}
- **Enemies:** ${enemies.length}
- **Collectibles:** ${coins.length}
- **Obstacles:** ${obstacles.length}
- **Audio Assets:** ${project.sounds?.length || 0} sound effects configured

---

## 🚀 Quick Start & How to Play

### Option A: Open with Godot 4
1. Download or clone this repository:
   \`\`\`bash
   git clone https://github.com/${cleanName}.git
   \`\`\`
2. Open **Godot 4.x** (v4.0 or newer).
3. Click **Import**, browse to this directory, and select \`project.godot\`.
4. Press **F5** to run the game!

### Option B: 1-Click Windows Runner
Double-click \`Run_Game.bat\` in the repository root. It automatically detects your local Java JDK or falls back to the native offline browser runner.

### Option C: Play in Browser (GitHub Pages)
1. Go to repository **Settings** -> **Pages**.
2. Select branch \`main\` and root folder \`/\`.
3. Click **Save** to deploy the playable web game!

---

## 🕹️ Controls
| Action | Keyboard Binding | Alternative |
| :--- | :--- | :--- |
| **Move Left / Right** | \`Arrow Left\` / \`Arrow Right\` | \`A\` / \`D\` |
| **Jump / Action** | \`Arrow Up\` / \`Space\` | \`W\` |
| **Pause Game** | \`Escape\` / \`P\` | - |

---

## 📁 Repository Structure
\`\`\`
├── project.godot            # Official Godot 4 project configuration
├── Main.tscn                # Godot scene hierarchy & node tree
├── Scripts/
│   └── PlayerController.gd  # Godot GDScript player physics & controls
├── src/
│   └── Main.java            # Standalone 60FPS Java Swing engine
├── Run_Game.bat             # 1-Click Windows launcher
├── index.html               # Playable standalone Web version
├── project.json             # Godot Studio project data interchange
├── build.gradle             # Gradle Java build automation
├── pom.xml                  # Maven Java build automation
└── .gitignore               # Godot & Java build ignore rules
\`\`\`

## 📜 License
Distributed under the MIT License. See \`LICENSE\` for more information.
`;

  // 7. Standard Godot & Java .gitignore
  const gitignoreContent = `# Godot 4+ specific ignores
.godot/
*.translation

# Java / Maven / Gradle ignores
bin/
build/
target/
.gradle/
*.class
*.jar
*.war

# OS metadata
.DS_Store
Thumbs.db
`;

  // 8. MIT LICENSE
  const licenseContent = `MIT License

Copyright (c) ${new Date().getFullYear()} ${project.name} Contributors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
`;

  // 9. Full raw project.json
  const projectJson = JSON.stringify(project, null, 2);

  // 10. Run_Game.bat
  const runBatch = generateWindowsBatchScript(project);

  // 11. build.gradle
  const buildGradle = generateGradleBuild(project);

  // 12. pom.xml
  const pomXml = generateMavenPom(project);

  return [
    {
      path: 'README.md',
      content: readmeContent,
      description: 'Project documentation, controls, and launch instructions',
      category: 'docs',
      included: true
    },
    {
      path: 'project.godot',
      content: godotProjectConfig,
      description: 'Godot 4.3 official engine configuration',
      category: 'engine',
      included: true
    },
    {
      path: 'Main.tscn',
      content: godotMainScene,
      description: 'Godot main 2D scene hierarchy and node definitions',
      category: 'engine',
      included: true
    },
    {
      path: 'Scripts/PlayerController.gd',
      content: playerGdScript,
      description: 'Godot GDScript character movement and physics logic',
      category: 'engine',
      included: true
    },
    {
      path: 'src/Main.java',
      content: javaSource,
      description: 'Native 60FPS Java Swing desktop game source',
      category: 'source',
      included: true
    },
    {
      path: 'index.html',
      content: webGameHtml,
      description: 'Standalone browser-playable HTML5 game canvas',
      category: 'web',
      included: true
    },
    {
      path: 'project.json',
      content: projectJson,
      description: 'Godot Studio project interchange metadata',
      category: 'config',
      included: true
    },
    {
      path: 'Run_Game.bat',
      content: runBatch,
      description: '1-Click Windows batch script launcher',
      category: 'source',
      included: true
    },
    {
      path: 'build.gradle',
      content: buildGradle,
      description: 'Gradle build automation script',
      category: 'config',
      included: true
    },
    {
      path: 'pom.xml',
      content: pomXml,
      description: 'Maven build descriptor file',
      category: 'config',
      included: true
    },
    {
      path: '.gitignore',
      content: gitignoreContent,
      description: 'Git ignore rules for Godot and Java artifacts',
      category: 'config',
      included: true
    },
    {
      path: 'LICENSE',
      content: licenseContent,
      description: 'Open source MIT software license',
      category: 'docs',
      included: true
    }
  ];
}

// Helpers
function hexToRgbNormalized(hex: string): string {
  if (!hex || !hex.startsWith('#')) return '0.2, 0.5, 0.9, 1';
  let c = hex.substring(1);
  if (c.length === 3) c = c.split('').map(x => x + x).join('');
  const num = parseInt(c, 16);
  const r = ((num >> 16) & 255) / 255;
  const g = ((num >> 8) & 255) / 255;
  const b = (num & 255) / 255;
  return `${r.toFixed(2)}, ${g.toFixed(2)}, ${b.toFixed(2)}, 1`;
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

// =========================================================================
// GITHUB REST API CLIENT
// =========================================================================

/**
 * Validates a GitHub Personal Access Token or OAuth Token
 */
export async function verifyGitHubToken(token: string): Promise<GitHubUser> {
  const cleanToken = token.trim();
  const response = await fetch('https://api.github.com/user', {
    headers: {
      Authorization: `Bearer ${cleanToken}`,
      Accept: 'application/vnd.github.v3+json'
    }
  });

  if (!response.ok) {
    if (response.status === 401) {
      throw new Error('Invalid GitHub token. Please check the token permissions and try again.');
    }
    const err = await response.json().catch(() => ({}));
    throw new Error(err.message || `GitHub authentication error: ${response.statusText}`);
  }

  return response.json();
}

/**
 * Retrieves the user's available repositories
 */
export async function fetchUserRepositories(token: string): Promise<GitHubRepo[]> {
  const cleanToken = token.trim();
  const response = await fetch('https://api.github.com/user/repos?sort=updated&per_page=100&type=all', {
    headers: {
      Authorization: `Bearer ${cleanToken}`,
      Accept: 'application/vnd.github.v3+json'
    }
  });

  if (!response.ok) {
    const err = await response.json().catch(() => ({}));
    throw new Error(err.message || 'Failed to fetch repositories from GitHub.');
  }

  return response.json();
}

/**
 * Creates a brand-new repository on GitHub
 */
export async function createGitHubRepository(
  token: string,
  repoName: string,
  description: string,
  isPrivate: boolean
): Promise<GitHubRepo> {
  const cleanToken = token.trim();
  const cleanName = repoName.trim().replace(/\s+/g, '-').replace(/[^a-zA-Z0-9._-]/g, '');

  if (!cleanName) {
    throw new Error('Repository name cannot be empty.');
  }

  const response = await fetch('https://api.github.com/user/repos', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${cleanToken}`,
      Accept: 'application/vnd.github.v3+json',
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      name: cleanName,
      description: description.trim() || '2D game project created with Godot Engine Studio',
      private: isPrivate,
      auto_init: true // Creates an initial commit with README so main branch exists
    })
  });

  if (!response.ok) {
    const err = await response.json().catch(() => ({}));
    throw new Error(err.message || `Failed to create repository "${cleanName}".`);
  }

  return response.json();
}

/**
 * Fetches the existing file SHA if the file already exists in the repository.
 */
async function getExistingFileSha(
  token: string,
  owner: string,
  repo: string,
  path: string,
  branch: string
): Promise<string | null> {
  try {
    const response = await fetch(
      `https://api.github.com/repos/${owner}/${repo}/contents/${encodeURIComponent(path)}?ref=${encodeURIComponent(branch)}`,
      {
        headers: {
          Authorization: `Bearer ${token.trim()}`,
          Accept: 'application/vnd.github.v3+json'
        }
      }
    );
    if (response.ok) {
      const data = await response.json();
      return data.sha || null;
    }
    return null;
  } catch {
    return null;
  }
}

/**
 * Pushes all selected game project files directly to the GitHub repository.
 */
export async function pushProjectToGitHub(
  token: string,
  owner: string,
  repo: string,
  branch: string,
  commitMessage: string,
  files: GitHubFileToPush[],
  onProgress?: (progress: PushProgress) => void
): Promise<{ success: boolean; repoUrl: string; totalPushed: number }> {
  const cleanToken = token.trim();
  const activeFiles = files.filter(f => f.included);

  if (activeFiles.length === 0) {
    throw new Error('No files selected for pushing.');
  }

  onProgress?.({
    currentFileIndex: 0,
    totalFiles: activeFiles.length,
    currentFileName: '',
    status: 'preparing',
    message: `Preparing ${activeFiles.length} files for repository ${owner}/${repo}...`,
    percentage: 5
  });

  // Verify repository access
  const repoCheck = await fetch(`https://api.github.com/repos/${owner}/${repo}`, {
    headers: {
      Authorization: `Bearer ${cleanToken}`,
      Accept: 'application/vnd.github.v3+json'
    }
  });

  if (!repoCheck.ok) {
    const err = await repoCheck.json().catch(() => ({}));
    throw new Error(`Cannot access repository "${owner}/${repo}": ${err.message || repoCheck.statusText}`);
  }

  const repoData = await repoCheck.json();
  const targetBranch = branch.trim() || repoData.default_branch || 'main';

  let pushedCount = 0;

  for (let i = 0; i < activeFiles.length; i++) {
    const file = activeFiles[i];
    const percentage = Math.round(10 + ((i) / activeFiles.length) * 85);

    onProgress?.({
      currentFileIndex: i + 1,
      totalFiles: activeFiles.length,
      currentFileName: file.path,
      status: 'uploading',
      message: `Pushing (${i + 1}/${activeFiles.length}): ${file.path}...`,
      percentage
    });

    // Check if the file already exists on this branch to retrieve SHA for update
    const existingSha = await getExistingFileSha(cleanToken, owner, repo, file.path, targetBranch);

    const bodyPayload: any = {
      message: `${commitMessage.trim() || 'Add game project files'} [${file.path}]`,
      content: utf8ToBase64(file.content),
      branch: targetBranch
    };

    if (existingSha) {
      bodyPayload.sha = existingSha;
    }

    const putRes = await fetch(
      `https://api.github.com/repos/${owner}/${repo}/contents/${file.path}`,
      {
        method: 'PUT',
        headers: {
          Authorization: `Bearer ${cleanToken}`,
          Accept: 'application/vnd.github.v3+json',
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(bodyPayload)
      }
    );

    if (!putRes.ok) {
      const err = await putRes.json().catch(() => ({}));
      throw new Error(`Failed to commit file "${file.path}": ${err.message || putRes.statusText}`);
    }

    pushedCount++;
  }

  const finalRepoUrl = `https://github.com/${owner}/${repo}`;

  onProgress?.({
    currentFileIndex: activeFiles.length,
    totalFiles: activeFiles.length,
    currentFileName: 'Done',
    status: 'completed',
    message: `Successfully pushed all ${pushedCount} files to ${owner}/${repo} on branch "${targetBranch}"!`,
    percentage: 100,
    repoUrl: finalRepoUrl,
    branchName: targetBranch
  });

  return {
    success: true,
    repoUrl: finalRepoUrl,
    totalPushed: pushedCount
  };
}
